# Generated by Django 3.2.7 on 2021-09-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('best_rank', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
