# Generated by Django 3.2.7 on 2021-09-09 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('rank', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('tracked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trackeduser')),
            ],
        ),
    ]
